# Site Settings
title: Jonathan Herbert
email: ""
description: >-
  Jonathan Herbert's GitHub Page
url: "https://foohyfooh.github.io"
github_username: foohyfooh

# Build Settings
markdown: kramdown
theme: minima
header_pages:
  - pages/posts.md
  - pages/pokemon.md
plugins:
  - jekyll-feed
  - jekyll-redirect-from
sass:
  style: compressed
highlighter: rouge

# Collection Settigs
collections:
  posts:
      output: true
      permalink: /posts/:year/:month/:day/:title
