# Site Settings
title: Jonathan Herbert
email: ""
description: >-
  Jonathan Herbert's GitHub page
url: "https://foohyfooh.github.io"
github_username: foohyfooh

# Build Settings
markdown: kramdown
theme: minima
header_pages:
  - posts.md
  - pages/Nekkra-Pokemon-Spotlights.md
plugins:
  - jekyll-feed
sass:
  style: compressed
highlighter: rouge

# Collection Settigs
collections:
  posts:
      output: true
      permalink: /posts/:year/:month/:day/:title
